// 语言表与统一语言工具（构建期 layout 注入 window.__LANGS__；缺省回退 zh/en）。
// 判定顺序：data-lang（i18n 运行时写入）→ <html lang> BCP 47 前缀 → URL 前缀 → 默认语言。
// window.langOf/__langSeg/__langPrefix/__langStrip 为全站唯一实现，ESM 侧经 js/core/lang.js 取用。
window.__LANGS__=(function(){var L=Array.isArray(window.__LANGS__)?window.__LANGS__.filter(function(x){return typeof x==='string'&&x}):[];return L.length?L:['zh','en']})();
window.__DEFAULT_LANG__=window.__LANGS__[0]||'zh';
window.__langSeg=function(pathname){var p=String(pathname||'');var L=window.__LANGS__;for(var i=0;i<L.length;i++){var l=String(L[i]);if(p==='/'+l||p.indexOf('/'+l+'/')===0)return l}return ''};
window.langOf=function(){try{var el=document.documentElement;var dl=el&&el.getAttribute?el.getAttribute('data-lang'):'';if(dl)return dl;var html=(el&&el.getAttribute?el.getAttribute('lang'):'')||'';var L=window.__LANGS__;for(var i=0;i<L.length;i++){if(html.toLowerCase().indexOf(String(L[i]).toLowerCase())===0)return L[i]}var seg=window.__langSeg((window.location&&window.location.pathname)||'');return seg||window.__DEFAULT_LANG__||'zh'}catch(e){return window.__DEFAULT_LANG__||'zh'}};
window.__langPrefix=function(){return '/'+window.langOf()+'/'};
window.__langStrip=function(pathname){var p=String(pathname||'');var seg=window.__langSeg(p);if(!seg)return p;var rest=p.slice(seg.length+1);return rest.charAt(0)==='/'?rest:'/'+rest};
window.__T=function(k,d){try{var D=window.__I18N__||{};var LANG=window.langOf();var dk=(LANG!=='zh'&&D[LANG])?D[LANG]:(LANG==='en'?D.en||{}:D)||{};var v=dk;var ps=String(k).split('.');for(var i=0;i<ps.length;i++){if(v&&typeof v==='object')v=v[ps[i]];else{v=undefined;break}}if(v===undefined||v===null||v==='')return d||'';return v}catch(e){return d||''}};
window.__SB=function(){try{var S=(window.__FEATURES__||{}).scrollBehavior||{};if(S.enabled===false)return 'auto';if(document.documentElement.classList.contains('save-data'))return 'auto';if(S.respectReducedMotion!==false&&window.matchMedia('(prefers-reduced-motion: reduce)').matches)return 'auto';return S.behavior||'smooth'}catch(e){return 'smooth'}};
window.__toast=function(msg,opts){try{var T=(window.__FEATURES__||{}).toast||{};if(T.enabled===false)return false;opts=opts||{};var wrap=document.getElementById('toastWrap');if(!wrap){wrap=document.createElement('div');wrap.id='toastWrap';wrap.className='toast-container';wrap.setAttribute('role','status');wrap.setAttribute('aria-live','polite');document.body.appendChild(wrap)}wrap.setAttribute('data-pos',T.position);var max=+T.maxVisible;var nodes=wrap.querySelectorAll('.toast');while(nodes.length>=max){nodes[0].remove();nodes=wrap.querySelectorAll('.toast')}var el=document.createElement('div');el.className='toast toast-'+(opts.type||'info');el.textContent=String(msg||'');wrap.appendChild(el);requestAnimationFrame(function(){el.classList.add('show')});var dur=isNaN(+opts.duration)?+T.durationMs:+opts.duration;setTimeout(function(){el.classList.remove('show');setTimeout(function(){el.remove()},+T.removeDelayMs)},dur);return true}catch(e){return false}};
// 外置运行时配置异步加载（fail-open）：成功后写入全部全局并置 __CONFIG_OK__=true；
// 失败重试 1 次，仍失败或超时（features.boot.configTimeoutMs，经 __CONFIG_TIMEOUT__ 注入）则应用内联降级子集 __CRIT__（__CONFIG_OK__=false），页面继续可用。
// 注入缺失/非法（≤0）时按 0 处理：立即降级为 __CRIT__（安全优先，不静默使用陈旧缺省值）。
// 该 Promise 永不 reject；boot.js 等待 __CONFIG_READY__ 后再调度队列。
window.__CONFIG_READY__=(function(){var URL=window.__CONFIG_URL__||'',CRIT=window.__CRIT__||{},TIMEOUT=Number(window.__CONFIG_TIMEOUT__);if(!(TIMEOUT>0))TIMEOUT=0;
function applyCrit(C){C=C||{};window.__FEATURES__=C.features||{};var P=C.pwa||{};window.__PWA_ON__=P.enabled===true;window.__PWA_SW__=P.serviceWorker||''}
function applyExt(C){window.__FEATURES__=C.features||{};window.__TUNING__=C.tuning||{};if(C.guard)window.__GUARD__=C.guard;if(C.morphIcons)window.__MORPH__=C.morphIcons;if(C.presets)window.__PRESETS__=C.presets;if(C.quotes)window.__QUOTES__=C.quotes;if(C.i18n)window.__I18N__=C.i18n;if(C.linkWarning)window.__LINK_WARNING__=C.linkWarning;if(C.theme)window.__THEME__=C.theme;var P=C.pwa||{};window.__PWA_ON__=P.enabled===true;window.__PWA_SW__=P.serviceWorker||''}
function attempt(){return new Promise(function(resolve,reject){if(!URL||typeof fetch!=='function'){reject(new Error('config url unavailable'));return}fetch(URL,{credentials:'same-origin'}).then(function(r){if(!r.ok)throw new Error('HTTP '+r.status);return r.json()}).then(resolve,reject)})}
function degrade(){applyCrit(CRIT);window.__CONFIG_OK__=false;console.warn('[config] 外置配置加载失败，已降级为内置最小子集')}
return new Promise(function(resolve){var settled=false;var timer=setTimeout(function(){if(settled)return;settled=true;degrade();resolve()},TIMEOUT);
attempt().catch(function(){return attempt()}).then(function(C){if(settled)return;settled=true;clearTimeout(timer);if(C&&typeof C==='object'){applyExt(C);window.__CONFIG_OK__=true}else{degrade()}resolve()},function(){if(settled)return;settled=true;clearTimeout(timer);degrade();resolve()})})})();
