export function init() {var F=window.__FEATURES__||{},SB=(F&&F.sidebarDrag)||{};if(SB.enabled===false)return;var aside=document.querySelector('.sidebar');if(!aside)return;var slots=aside.querySelectorAll('.sidebar-widget');if(slots.length<2)return;var KEY=SB.storageKey;function wrap(){Array.prototype.forEach.call(slots,function(w){if(w.parentNode.classList.contains('sidebar-widget-slot'))return;var slot=document.createElement('div');slot.className='sidebar-widget-slot';slot.setAttribute('data-widget-type',(w.className.match(/widget-(\w+)/)||[])[1]||'x');var handle=document.createElement('span');handle.className='drag-handle';handle.innerHTML='&equiv;';handle.title=__T('toolbar.dragSort','拖动以排序');handle.setAttribute('aria-label',__T('toolbar.dragSort','拖动排序'));w.parentNode.insertBefore(slot,w);slot.appendChild(handle);slot.appendChild(w);w.setAttribute('draggable','true');w.addEventListener('dragstart',function(e){e.dataTransfer.setData('text/plain','1');slot.classList.add('dragging')});w.addEventListener('dragend',function(){slot.classList.remove('dragging');save()});w.addEventListener('dragover',function(e){e.preventDefault();e.stopPropagation();slot.classList.add('drag-over')});w.addEventListener('dragleave',function(){slot.classList.remove('drag-over')});w.addEventListener('drop',function(e){e.preventDefault();var from=document.querySelector('.sidebar-widget-slot.dragging');if(!from||from===slot)return;var parent=aside;from.parentNode.removeChild(from);if(slot.nextSibling)parent.insertBefore(from,slot.nextSibling);else parent.appendChild(from);slot.classList.remove('drag-over');save()})});}
function save(){var arr=[];Array.prototype.forEach.call(aside.querySelectorAll('.sidebar-widget-slot'),function(sl){arr.push(sl.getAttribute('data-widget-type'))});try{localStorage.setItem(KEY,JSON.stringify(arr))}catch(e){}}
function restore(){var arr=null;try{arr=JSON.parse(localStorage.getItem(KEY)||'null')}catch(e){arr=null}if(!arr||!arr.length)return;Array.prototype.forEach.call(arr,function(t){var src=aside.querySelector('.sidebar-widget-slot[data-widget-type="'+t+'"]');if(src){aside.removeChild(src);aside.appendChild(src)}})}
wrap();restore();

var touchTimer=null,touchSlot=null;
Array.prototype.forEach.call(aside.querySelectorAll('.sidebar-widget-slot'),function(sl){var w=sl.querySelector('.sidebar-widget');if(!w)return;
w.addEventListener('touchstart',function(e){if(e.touches.length!==1)return;touchSlot=sl;touchTimer=setTimeout(function(){touchSlot.classList.add('dragging');if(navigator.vibrate)navigator.vibrate(10)},500)},{passive:true});
w.addEventListener('touchmove',function(e){if(!touchSlot||!touchSlot.classList.contains('dragging'))return;e.preventDefault();var touch=e.touches[0];var el=document.elementFromPoint(touch.clientX,touch.clientY);if(!el)return;var slot=el.closest?el.closest('.sidebar-widget-slot'):null;if(slot&&slot!==touchSlot){var y=touch.clientY;var rect=slot.getBoundingClientRect();if(y<rect.top+rect.height/2){aside.insertBefore(touchSlot,slot)}else{aside.insertBefore(touchSlot,slot.nextSibling)}}},{passive:false});
w.addEventListener('touchend',function(){if(touchTimer){clearTimeout(touchTimer);touchTimer=null}if(touchSlot){touchSlot.classList.remove('dragging');touchSlot=null;save()}});
w.addEventListener('touchcancel',function(){if(touchTimer){clearTimeout(touchTimer);touchTimer=null}if(touchSlot){touchSlot.classList.remove('dragging');touchSlot=null}})});
}
