// S-ynapse Security Worker — runs at the Cloudflare Worker edge.
// Provides: rate limiting, CSP headers, HTTP→HTTPS redirect, path blocking.
// This is a dynamic security layer that runs before Cloudflare Pages serves the static assets.
//
// CONFIG SOURCE: workers/security-config.js (AUTO-GENERATED by `npm run build` from
// security.json5 — the single source of truth). Edit security.json5, never this file's config.
// If the generated file is missing (e.g. prototype deploy without build), built-in FALLBACK
// below keeps a safe baseline — but rate limits/thresholds will then NOT match security.json5.
//
// Relationship to `_headers`: both layers are generated from security.json5 and apply the same
// directives. Static `_headers` covers all paths on Pages; this Worker adds the dynamic parts
// (rate limiting, path blocking, HTTPS redirect, CSP report endpoint) at the edge.

import { ipMatchesAny, isPathBlocked } from "./lib/ip-utils.mjs";
import { RateLimiter, isStaticAsset } from "./lib/rate-limit.mjs";

const DEFAULT_SKIP_PATHS = ["/assets/", "/media/", "/og/", "/icons/", "/pagefind/"];
const CSP_REPORT_MAX_BYTES = 16384;

const limiter = new RateLimiter(5000);

// Safety baseline when security-config.js is absent — mirrors the repo defaults.
const FALLBACK = {
  rateLimiting: {
    enabled: true,
    maxRequests: 100,
    windowMs: 60000,
    blockDuration: 300000,
    whitelist: [],
    blacklist: [],
    skipPaths: DEFAULT_SKIP_PATHS
  },
  csp: {
    directives: {
      "default-src": ["'self'"],
      // 无 security-config.js 时没有构建期 nonce 可用：按 fail-closed 收紧，移除
      // 'unsafe-inline'（模板内联事件已全部改为 addEventListener）。代价是兜底场景下
      // 普通页面的构建期内联脚本会被拦截——安全优先，正式产物（含 nonce）会覆盖本兜底。
      "script-src": ["'self'", "'inline-speculation-rules'"],
      // 兜底无 nonce 可注入 <style>，故 style-src 保留 'unsafe-inline' 保障降级页
      // （服务不可用/维护页）样式可读；正式产物由构建期 nonce 替换本项。
      "style-src": ["'self'", "'unsafe-inline'"],
      // 内联 style 属性不受 nonce 约束（CSP 规范不支持），兜底与正式产物均需放行。
      "style-src-attr": ["'unsafe-inline'"],
      "img-src": ["'self'", "data:", "https:"],
      "font-src": ["'self'", "https://fonts.gstatic.com"],
      "object-src": ["'none'"],
      "frame-src": ["https://giscus.app"]
    },
    reportOnly: false,
    reportUri: "/csp-report"
  },
  pathRestrictions: ["/admin/*"],
  forceHttps: true,
  headers: {
    "X-Frame-Options": "DENY",
    "X-Content-Type-Options": "nosniff",
    "Referrer-Policy": "strict-origin-when-cross-origin",
    "Permissions-Policy": "geolocation=(), microphone=(), camera=()",
    "Strict-Transport-Security": "max-age=31536000; includeSubDomains; preload",
    "X-XSS-Protection": "0"
  }
};

let CONFIG = FALLBACK;
try {
  const generated = await import("./security-config.js");
  if (generated && generated.default) CONFIG = generated.default;
} catch (err) {
  console.warn("[security-worker] security-config.js not found — using built-in FALLBACK. Run `npm run build` to generate it from security.json5.");
}

// Config resolution: an explicitly configured empty array is meaningful —
// pathRestrictions: [] means "no restricted paths", skipPaths: [] means
// "count every request". Only missing fields fall back to the fail-closed
// built-ins (used when security-config.js is absent).
function resolveWorkerConfig(config) {
  const cfg = config && typeof config === "object" ? config : {};
  const rl = cfg.rateLimiting || FALLBACK.rateLimiting;
  const cspConfig = cfg.csp || FALLBACK.csp;
  const blockedRules = Array.isArray(cfg.pathRestrictions) ? cfg.pathRestrictions : FALLBACK.pathRestrictions;
  const skipPaths = Array.isArray(rl.skipPaths) ? rl.skipPaths : DEFAULT_SKIP_PATHS;
  return { rl, cspConfig, blockedRules, skipPaths };
}

const { rl, cspConfig, blockedRules, skipPaths } = resolveWorkerConfig(CONFIG);

/**
 * 解析 Accept-Language，判断首选具体语言是否为英语（RFC 4647 基本过滤的简化实现）：
 * 按 q 值降序、同 q 保持请求顺序，取第一个具体语言标签的基础子标签比较（en-US → en）；
 * "*" 与空值视为中文（站点默认语言）。仅用于维护页默认文案，不用于内容协商缓存。
 */
function prefersEnglish(acceptLanguage) {
  const entries = String(acceptLanguage || "")
    .split(",")
    .map(function (part, index) {
      const segments = part.trim().split(";");
      const qMatch = /q\s*=\s*([0-9.]+)/i.exec(segments.slice(1).join(";"));
      const qValue = qMatch ? Number(qMatch[1]) : 1;
      return { tag: (segments[0] || "").trim().toLowerCase(), q: Number.isFinite(qValue) ? qValue : 1, index: index };
    })
    .filter(function (entry) { return entry.tag && entry.tag !== "*"; });
  entries.sort(function (a, b) { return (b.q - a.q) || (a.index - b.index); });
  if (entries.length === 0) return false;
  return entries[0].tag.split("-")[0] === "en";
}

/** 从生效 CSP 配置提取 style-src(elem) 的构建期 nonce；FALLBACK（无 nonce）时返回空串。 */
function getStyleNonce() {
  const directives = (cspConfig && cspConfig.directives) || {};
  for (const name of ["style-src-elem", "style-src"]) {
    const list = Array.isArray(directives[name]) ? directives[name] : [];
    for (const value of list) {
      const match = /^'nonce-([^']+)'$/.exec(String(value));
      if (match) return match[1];
    }
  }
  return "";
}

/**
 * 维护页文案：默认中英双语内置，按 Accept-Language 选择（en* → 英文，其余 → 中文）；
 * 自定义 MAINTENANCE_MESSAGE 原样覆盖正文（输出前 HTML 转义）。<style> 仅在生效 CSP
 * 含构建期 nonce 时注入同一 nonce（FALLBACK 无 nonce，依赖 style-src 'unsafe-inline'）。
 */
function maintenanceCopy(acceptLanguage, env) {
  const en = prefersEnglish(acceptLanguage);
  const custom = env && env.MAINTENANCE_MESSAGE ? String(env.MAINTENANCE_MESSAGE) : "";
  const rawMessage = custom || (en ? "The site is under maintenance. Please check back later." : "本站正在维护中，请稍后再来。");
  const heading = en ? "Maintenance" : "维护中";
  const nonce = getStyleNonce();
  return {
    lang: en ? "en" : "zh-CN",
    title: escapeHtml(heading + " - " + rawMessage),
    heading: escapeHtml(heading),
    message: escapeHtml(rawMessage),
    nonceAttr: nonce ? ' nonce="' + escapeHtml(nonce) + '"' : ""
  };
}

// —— 结构化日志（RFC 5424 严重度映射；JSON Lines 单行输出）——
// 级别：off(0) < error(1) < warn(2) < info(3) < debug(4)；环境变量 LOG_LEVEL 控制（默认 info）。
// 字段：ts(UTC ISO)/level/module/requestId/event + 事件附加字段；字符串字段去除换行并限长，
// 不落 IP/UA 明文（需要关联时用 ipHash 前 12 位十六进制）。默认 SHA-256(ip|固定盐)，
// 固定盐可被枚举反查；配置 LOG_IP_SECRET 后改用 HMAC-SHA256（推荐生产启用）。
const LOG_LEVELS = { off: 0, error: 1, warn: 2, info: 3, debug: 4 };

function makeLog(env, requestId) {
  const raw = env && env.LOG_LEVEL ? String(env.LOG_LEVEL).toLowerCase() : "info";
  const level = Object.prototype.hasOwnProperty.call(LOG_LEVELS, raw) ? LOG_LEVELS[raw] : LOG_LEVELS.info;
  function emit(lv, event, fields) {
    if (LOG_LEVELS[lv] > level) return;
    const line = { ts: new Date().toISOString(), level: lv, module: "security-worker", requestId: requestId, event: event };
    if (fields && typeof fields === "object") {
      for (const k of Object.keys(fields)) {
        const v = fields[k];
        if (v === undefined || v === null || v === "") continue;
        line[k] = typeof v === "string" ? v.replace(/[\r\n]+/g, " ").slice(0, 512) : v;
      }
    }
    const out = JSON.stringify(line);
    if (lv === "error") console.error(out);
    else if (lv === "warn") console.warn(out);
    else console.log(out);
  }
  return {
    error: (event, fields) => emit("error", event, fields),
    warn: (event, fields) => emit("warn", event, fields),
    info: (event, fields) => emit("info", event, fields),
    debug: (event, fields) => emit("debug", event, fields)
  };
}

/** 返回 IP 的短哈希（日志关联用，不可逆；仅当 crypto.subtle 可用时）。 */
async function hashIp(ip, env) {
  if (!ip) return undefined;
  try {
    const enc = new TextEncoder();
    const secret = env && env.LOG_IP_SECRET ? String(env.LOG_IP_SECRET) : "";
    let buf;
    if (secret) {
      const key = await crypto.subtle.importKey("raw", enc.encode(secret), { name: "HMAC", hash: "SHA-256" }, false, ["sign"]);
      buf = await crypto.subtle.sign("HMAC", key, enc.encode(ip));
    } else {
      buf = await crypto.subtle.digest("SHA-256", enc.encode(ip + "|s-ynapse-log"));
    }
    return Array.from(new Uint8Array(buf)).map((b) => b.toString(16).padStart(2, "0")).join("").slice(0, 12);
  } catch (e) {
    return undefined;
  }
}

function escapeHtml(value) {
  return String(value).replace(/[&<>"']/g, (c) => ({
    "&": "&amp;",
    "<": "&lt;",
    ">": "&gt;",
    '"': "&quot;",
    "'": "&#39;"
  })[c]);
}

function buildCsp() {
  const directives = [];
  for (const [key, vals] of Object.entries(cspConfig.directives || {})) {
    if (Array.isArray(vals) && vals.length > 0) {
      directives.push(`${key} ${vals.join(" ")}`);
    }
  }
  if (directives.length === 0) return null;
  if (cspConfig.reportUri) directives.push(`report-uri ${cspConfig.reportUri}`);
  return {
    name: cspConfig.reportOnly ? "Content-Security-Policy-Report-Only" : "Content-Security-Policy",
    value: directives.join("; ")
  };
}

function baseHeaders(extra) {
  const headers = new Headers();
  for (const [name, value] of Object.entries(CONFIG.headers || {})) {
    headers.set(name, value);
  }
  const csp = buildCsp();
  if (csp) headers.set(csp.name, csp.value);
  if (extra) {
    for (const [name, value] of Object.entries(extra)) headers.set(name, value);
  }
  return headers;
}

function edgeResponse(body, status, extra, requestId) {
  const headers = baseHeaders(extra);
  if (requestId) headers.set("X-Request-Id", requestId);
  return new Response(body, { status, headers });
}

async function handleRequest(request, env) {
  const url = new URL(request.url);
  const clientIP = request.headers.get("CF-Connecting-IP");
  // 请求关联 ID：优先复用 Cloudflare 的 CF-Ray，缺失时生成 UUID；随响应头 X-Request-Id 回传，
  // 日志与响应可对同一请求串联排查（W3C Trace Context 思路，边缘侧自生成即不依赖上游）。
  const requestId = request.headers.get("CF-Ray") || crypto.randomUUID();
  const log = makeLog(env, requestId);

  // Maintenance mode — enabled by setting env var MAINTENANCE=1 (e.g. via wrangler deploy).
  // Default notice is bilingual and picked by Accept-Language (en* → English, otherwise
  // Chinese); optional env var MAINTENANCE_MESSAGE overrides the notice verbatim (HTML-escaped).
  if (env && env.MAINTENANCE === "1") {
    log.info("maintenance_served", { path: url.pathname });
    const copy = maintenanceCopy(request.headers.get("Accept-Language"), env);
    const html = `<!DOCTYPE html><html lang="${copy.lang}"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${copy.title}</title><style${copy.nonceAttr}>body{display:flex;align-items:center;justify-content:center;height:100vh;margin:0;font-family:system-ui,-apple-system,'Segoe UI',sans-serif;background:#f7fafc;color:#1a202c}h1{font-weight:700}p{color:#4a5568}</style></head><body><main><h1>${copy.heading}</h1><p>${copy.message}</p></main></body></html>`;
    return edgeResponse(html, 503, {
      "Content-Type": "text/html; charset=utf-8",
      "Retry-After": "3600",
      "Cache-Control": "no-store"
    }, requestId);
  }

  // HTTP→HTTPS redirect in production only (local dev uses HTTP)
  if (CONFIG.forceHttps && url.protocol !== "https:" && env && env.ENVIRONMENT === "production") {
    url.protocol = "https:";
    log.debug("https_redirect", { path: url.pathname });
    return edgeResponse(null, 301, { Location: url.toString() }, requestId);
  }

  if (rl.enabled) {
    // Fail-closed: when CF-Connecting-IP is absent (non-Cloudflare front), requests
    // share a single bucket instead of skipping rate limiting entirely.
    const rateKey = clientIP || "unknown-ip";
    // Blacklist entries (IP or CIDR) are always blocked — checked before the sliding window.
    if (clientIP && ipMatchesAny(clientIP, rl.blacklist)) {
      log.warn("ip_blacklisted", { ipHash: await hashIp(clientIP, env), path: url.pathname });
      return edgeResponse("Forbidden", 403, undefined, requestId);
    }
    const whitelisted = clientIP ? ipMatchesAny(clientIP, rl.whitelist) : false;
    const assetRequest = (request.method === "GET" || request.method === "HEAD") && isStaticAsset(url.pathname, skipPaths);
    if (!whitelisted && !assetRequest) {
      const verdict = limiter.check(rateKey, rl);
      if (verdict === "blocked" || verdict === "limited") {
        const retryAfter = String(Math.ceil((Number(rl.blockDuration) || 300000) / 1000));
        log.warn("rate_limited", { ipHash: await hashIp(clientIP, env), path: url.pathname, verdict: verdict, retryAfter: retryAfter });
        return edgeResponse("Too Many Requests", 429, { "Retry-After": retryAfter }, requestId);
      }
    }
  }

  // CSP violation report endpoint — accepts POST from browsers and logs key fields.
  // Runs after rate limiting so anonymous floods cannot bypass the limit.
  const reportUri = cspConfig.reportUri || "/csp-report";
  if (url.pathname === reportUri && request.method === "POST") {
    let text;
    try {
      text = await request.text();
    } catch (e) {
      log.warn("csp_report_read_failed");
      return edgeResponse("Bad Request", 400, undefined, requestId);
    }
    if (text.length > CSP_REPORT_MAX_BYTES) {
      log.warn("csp_report_too_large", { bytes: text.length });
      return edgeResponse("Payload Too Large", 413, undefined, requestId);
    }
    try {
      const parsed = JSON.parse(text);
      const report = parsed && typeof parsed === "object" ? parsed : {};
      const body = report["csp-report"] || report.body || report;
      const fields = body && typeof body === "object" ? {
        documentUri: String(body["document-uri"] || body.documentURL || "").slice(0, 512),
        directive: String(body["violated-directive"] || body.effectiveDirective || body["effective-directive"] || "").slice(0, 256),
        blockedUri: String(body["blocked-uri"] || body.blockedURL || "").slice(0, 512)
      } : {};
      console.log("CSP Violation:", JSON.stringify(fields).replace(/[\r\n]+/g, " "));
      log.info("csp_violation", fields);
    } catch (e) {
      log.warn("csp_report_parse_failed");
    }
    return edgeResponse("ok", 200, { "Cache-Control": "no-store" }, requestId);
  }

  // Block restricted paths at the edge before they reach static assets.
  // Rules may carry allowedIPs (CIDR): matching clients bypass the block.
  const rule = isPathBlocked(url.pathname, blockedRules);
  if (rule) {
    const allowed = Array.isArray(rule.allowedIPs) && ipMatchesAny(clientIP, rule.allowedIPs);
    if (!allowed) {
      if (rule.requireAuth === true) {
        log.warn("path_blocked_require_auth", { rule: rule.path });
      }
      log.warn("path_blocked", { rule: rule.path, ipHash: await hashIp(clientIP, env) });
      return edgeResponse("Forbidden", 403, undefined, requestId);
    }
  }

  // Fetch the static asset from Cloudflare Pages
  let response;
  try {
    response = await env.ASSETS.fetch(request);
  } catch (err) {
    log.error("assets_fetch_failed", { error: err && err.message });
    return edgeResponse("Bad Gateway", 502, undefined, requestId);
  }

  // Attach security headers + CSP (same directives as _headers, from security.json5)
  const headers = new Headers(response.headers);
  for (const [name, value] of Object.entries(CONFIG.headers || {})) {
    headers.set(name, value);
  }
  const csp = buildCsp();
  if (csp) headers.set(csp.name, csp.value);
  headers.set("X-Request-Id", requestId);

  return new Response(response.body, {
    status: response.status,
    statusText: response.statusText,
    headers
  });
}

export { resolveWorkerConfig };
export default {
  fetch: handleRequest
};
