// S-ynapse Security Worker — runs at the Cloudflare Worker edge.
// Provides: rate limiting, CSP headers, HTTP→HTTPS redirect, path blocking.
// This is a dynamic security layer that runs before Cloudflare Pages serves the static assets.
//
// CONFIG SOURCE: workers/security-config.js (AUTO-GENERATED by `npm run build` from
// security.json — the single source of truth). Edit security.json, never this file's config.
// If the generated file is missing (e.g. prototype deploy without build), built-in FALLBACK
// below keeps a safe baseline — but rate limits/thresholds will then NOT match security.json.
//
// Relationship to `_headers`: both layers are generated from security.json and apply the same
// directives. Static `_headers` covers all paths on Pages; this Worker adds the dynamic parts
// (rate limiting, path blocking, HTTPS redirect, CSP report endpoint) at the edge.

const rateLimitMap = new Map();

// Safety baseline when security-config.js is absent — mirrors the repo defaults.
const FALLBACK = {
  rateLimiting: {
    enabled: true,
    maxRequests: 100,
    windowMs: 60000,
    blockDuration: 300000,
    whitelist: [],
    blacklist: []
  },
  csp: {
    directives: {
      "default-src": ["'self'"],
      "script-src": ["'self'", "'unsafe-inline'", "https://cdn.jsdelivr.net", "https://giscus.app"],
      "style-src": ["'self'", "'unsafe-inline'", "https://fonts.googleapis.com"],
      "img-src": ["'self'", "data:", "https:"],
      "font-src": ["'self'", "https://fonts.gstatic.com"],
      "object-src": ["'none'"],
      "frame-src": ["https://giscus.app"]
    },
    reportOnly: false,
    reportUri: "/csp-report"
  },
  pathRestrictions: ["/admin"],
  forceHttps: true,
  headers: {
    "X-Frame-Options": "DENY",
    "X-Content-Type-Options": "nosniff",
    "Referrer-Policy": "strict-origin-when-cross-origin",
    "Permissions-Policy": "geolocation=(), microphone=(), camera=()",
    "Strict-Transport-Security": "max-age=31536000; includeSubDomains; preload",
    "X-XSS-Protection": "1; mode=block"
  }
};

let CONFIG = FALLBACK;
try {
  const generated = await import("./security-config.js");
  if (generated && generated.default) CONFIG = generated.default;
} catch (err) {
  console.warn("[security-worker] security-config.js not found — using built-in FALLBACK. Run `npm run build` to generate it from security.json.");
}

const rl = CONFIG.rateLimiting || FALLBACK.rateLimiting;
const cspConfig = CONFIG.csp || FALLBACK.csp;
const blockedPaths = (Array.isArray(CONFIG.pathRestrictions) && CONFIG.pathRestrictions.length > 0
  ? CONFIG.pathRestrictions
  : FALLBACK.pathRestrictions).map((p) => (p.endsWith("/*") ? p.slice(0, -2) : p));

function isBlockedPath(pathname) {
  return blockedPaths.some((base) => base !== "/" && pathname.startsWith(base));
}

async function handleRequest(request, env) {
  const url = new URL(request.url);

  // Maintenance mode — enabled by setting env var MAINTENANCE=1 (e.g. via wrangler deploy).
  // Optional env var MAINTENANCE_MESSAGE customizes the notice.
  if (env && env.MAINTENANCE === "1") {
    const message = env.MAINTENANCE_MESSAGE || "本站正在维护中，请稍后再来。";
    return new Response(
      `<!DOCTYPE html><html lang="zh-CN"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>维护中 - ${message}</title><style>body{display:flex;align-items:center;justify-content:center;height:100vh;margin:0;font-family:system-ui,-apple-system,'Segoe UI',sans-serif;background:#f7fafc;color:#1a202c}h1{font-weight:700}p{color:#4a5568}</style></head><body><main><h1>🚧</h1><h1>维护中</h1><p>${message}</p></main></body></html>`,
      {
        status: 503,
        headers: {
          "Content-Type": "text/html; charset=utf-8",
          "Retry-After": "3600",
          "Cache-Control": "no-store",
        },
      }
    );
  }

  // Skip rate limiting when clientIP is null (not behind Cloudflare — e.g. local dev)
  // This prevents all local requests from sharing a single 'unknown' rate limit bucket.
  const clientIP = request.headers.get("CF-Connecting-IP");

  // HTTP→HTTPS redirect in production only (local dev uses HTTP)
  if (CONFIG.forceHttps && url.protocol !== "https:" && env.ENVIRONMENT === "production") {
    url.protocol = "https:";
    return Response.redirect(url.toString(), 301);
  }

  // CSP violation report endpoint — accepts POST from browsers and logs the report
  if (url.pathname === cspConfig.reportUri && request.method === "POST") {
    try {
      const report = await request.json();
      console.log("CSP Violation:", JSON.stringify(report));
    } catch (e) {
      console.warn("CSP report parse failed:", e.message);
    }
    return new Response("ok", { status: 200 });
  }

  if (rl.enabled && clientIP) {
    // Blacklist IPs are always blocked — checked before the sliding window.
    if (rl.blacklist.includes(clientIP)) {
      return new Response("Forbidden", { status: 403 });
    }
    // Whitelist IPs bypass rate limiting entirely.
    if (!rl.whitelist.includes(clientIP)) {
      const now = Date.now();
      const windowMs = rl.windowMs;
      const maxRequests = rl.maxRequests;
      const blockDuration = rl.blockDuration;

      let entry = rateLimitMap.get(clientIP);
      if (entry) {
        if (entry.blockedUntil && now < entry.blockedUntil) {
          return new Response("Too Many Requests", { status: 429 });
        }
        entry.hits = entry.hits.filter((t) => now - t < windowMs);
        if (entry.hits.length >= maxRequests) {
          entry.blockedUntil = now + blockDuration;
          return new Response("Too Many Requests", { status: 429 });
        }
        entry.hits.push(now);
      } else {
        rateLimitMap.set(clientIP, { hits: [now] });
      }
      // Lazy eviction when the map grows beyond 5000 entries.
      if (rateLimitMap.size > 5000) {
        for (const [ip, data] of rateLimitMap) {
          if (data.blockedUntil && data.blockedUntil < now) {
            rateLimitMap.delete(ip);
          } else {
            data.hits = data.hits.filter((t) => now - t < windowMs);
            if (data.hits.length === 0) rateLimitMap.delete(ip);
          }
        }
      }
    }
  }

  // Block restricted paths at the edge before they reach static assets
  if (isBlockedPath(url.pathname)) {
    return new Response("Forbidden", { status: 403 });
  }

  // Fetch the static asset from Cloudflare Pages
  const response = await env.ASSETS.fetch(request);

  // Attach security headers to the response (same directives as _headers, from security.json)
  const headers = new Headers(response.headers);
  for (const [name, value] of Object.entries(CONFIG.headers || {})) {
    headers.set(name, value);
  }

  // CSP header — report-only mode switches to the report-only header name.
  const cspDirectives = [];
  for (const [key, vals] of Object.entries(cspConfig.directives)) {
    if (Array.isArray(vals) && vals.length > 0) {
      cspDirectives.push(`${key} ${vals.join(" ")}`);
    }
  }
  if (cspDirectives.length > 0) {
    const cspHeader = cspConfig.reportOnly ? "Content-Security-Policy-Report-Only" : "Content-Security-Policy";
    headers.set(cspHeader, cspDirectives.join("; "));
  }

  return new Response(response.body, {
    status: response.status,
    statusText: response.statusText,
    headers,
  });
}

export default {
  fetch: handleRequest,
};
