name = "s-ynapse-security"
main = "security-worker.js"
compatibility_date = "2026-07-20"

[assets]
directory = "../dist"
binding = "ASSETS"
run_worker_first = true
not_found_handling = "404-page"

[env.production]
vars = { ENVIRONMENT = "production" }
