// 联系方式弹窗（点击社交图标打开；点击值块复制）。
// W4 接线：copyText(En) 作为值块复制按钮 title/aria-label；showAllItems=false 时超过 2 条折叠为「更多」展开器；
// popupWidth 由构建期模板写入 CSS（见 templates/site-css.ejs）。
function isEn() {
  var l = document.documentElement.getAttribute('data-lang') || ((document.documentElement.getAttribute('lang') || '').toLowerCase().indexOf('en') === 0 ? 'en' : 'zh');
  return l === 'en';
}
export function showContact(v,t,c){var o=document.getElementById('contactPopup'),tv=document.getElementById('contactPopupTitle'),cv=document.getElementById('contactPopupContent'),vw=document.getElementById('contactPopupValues');if(!o)return;tv.textContent=t;cv.textContent=c;var F=window.__FEATURES__||{},CPF=(F&&F.contactPopup)||{};var __en=isEn();var lbl=(__en?(CPF.copyTextEn||CPF.copyText):CPF.copyText)||__T('common.copy','复制');var mx=isNaN(+CPF.maxItems)?4:+CPF.maxItems;var items=String(v).split('\n').map(function(x){return x.trim()}).filter(Boolean);if(items.length>mx)items=items.slice(0,mx);var fold=CPF.showAllItems===false&&items.length>2;function addItem(x){var s=document.createElement('span');s.className='contact-popup-value';s.textContent=x;s.setAttribute('data-value',x);s.title=lbl;s.setAttribute('role','button');s.setAttribute('tabindex','0');s.setAttribute('aria-label',lbl);s.onclick=function(){copyContact(s)};s.onkeydown=function(e){if(e.key==='Enter'||e.key===' '){e.preventDefault();copyContact(s)}};vw.appendChild(s)}vw.innerHTML='';if(fold){var more=document.createElement('button');more.type='button';more.className='contact-popup-more';var expanded=false;var apply=function(){vw.innerHTML='';(expanded?items:items.slice(0,2)).forEach(addItem);more.textContent=expanded?__T('toolbar.collapseAll','收起'):__T('common.more','更多');vw.appendChild(more)};more.onclick=function(){expanded=!expanded;apply()};apply()}else{items.forEach(addItem)}o.hidden=false}
function copyContact(el){var v=el.getAttribute('data-value')||el.textContent;var F=window.__FEATURES__||{},CPF=(F&&F.contactPopup)||{};var __en=isEn();var txt=(__en&&CPF.copySuccessTextEn)?CPF.copySuccessTextEn:(CPF.copySuccessText||__T('toolbar.copyDoneToast','✓ 已复制到剪贴板'));var done=function(){if(window.__toast)window.__toast(txt,{type:'success'})};var fb=function(){var ta=document.createElement('textarea');ta.value=v;document.body.appendChild(ta);ta.select();try{document.execCommand('copy')}catch(e){/* 忽略：回退复制失败时仍关闭弹窗（主路径为 clipboard API） */}document.body.removeChild(ta);done()};if(navigator.clipboard&&navigator.clipboard.writeText){navigator.clipboard.writeText(v).then(done).catch(fb)}else{fb()}}
export function init() {
document.addEventListener('click',function(e){var el=e.target.closest('.js-contact');if(!el)return;e.preventDefault();showContact(el.getAttribute('data-contact')||'',el.getAttribute('data-title')||'',el.getAttribute('data-body')||'')});
var ov=document.getElementById('contactPopup');if(ov){ov.addEventListener('click',function(e){if(e.target===ov)ov.hidden=true});var cb=ov.querySelector('.contact-popup-footer .btn');if(cb)cb.addEventListener('click',function(){ov.hidden=true})}
}
